export const PLAYER_DETAIL_IMAGES: Record<string, string> = {
  "1496": "https://media.giphy.com/media/ppp9oIunS6o3az3TPH/giphy.gif",
  "133609": "https://media.giphy.com/media/EvB1Ctpabt0vbRJMKC/giphy.gif",
  "278": "https://media.giphy.com/media/zmnnWqFoMFOta5XQe9/giphy.gif",
  "762": "https://media.giphy.com/media/5F7D857WQjFIpalsHq/giphy.gif",
  "386828": "https://media.giphy.com/media/gcIrqAurIFpVA1LF5Y/giphy.gif",
  "10009": "https://media.giphy.com/media/8XhABAFGGzPueE7yvr/giphy.gif",
  "372": "https://media.giphy.com/media/wtIPJKK5nTlR1wWOSv/giphy.gif",
  "730": "https://media.giphy.com/media/aeXZZ4tjV6GMr2gjzt/giphy.gif",
  "283": "https://media.giphy.com/media/l580XJFTJ6zbSw1jAh/giphy.gif",
  "2285": "https://media.giphy.com/media/h1FKZTJsaSOqx0vthL/giphy.gif",
  "744": "https://media.giphy.com/media/I9KNlZKi1puKjGoBZe/giphy.gif",
  "129718": "https://media.giphy.com/media/EZ5SX3ZYRD05ynKiQQ/giphy.gif",
  "756": "https://media.giphy.com/media/Ql28EA1PSFUwxcq9U5/giphy.gif",
  "182718": "https://media.giphy.com/media/T4euFzhsf24H0SwMW6/giphy.gif",
  "101814": "https://media.giphy.com/media/SuUXTNkEXzWgI7IYY2/giphy.gif",
  "521": "https://media.giphy.com/media/9zcN6bEFEMRpPYiL56/giphy.gif",
  "909": "https://media.giphy.com/media/XsixdFneJHlz3scXli/giphy.gif",
  "1257": "https://media.giphy.com/media/77244AdKLUrSWYndao/giphy.gif",
  "619": "https://media.giphy.com/media/nex1l3149BkrQXFM5m/giphy.gif",
  "338958": "https://media.giphy.com/media/wvhFZvq3C42cOgu5dY/giphy.gif",
};
